<a href="https://colab.research.google.com/github/Raju-2004/Dinogame/blob/main/knn_alogorithm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
import pandas as pd
from sklearn.datasets import load_iris

In [4]:
data = pd.read_csv('/content/iris.csv')
data.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [5]:
data.corr()

sepal_length  sepal_width  petal_length  petal_width
sepal_length      1.000000    -0.109369      0.871754     0.817954
sepal_width      -0.109369     1.000000     -0.420516    -0.356544
petal_length      0.871754    -0.420516      1.000000     0.962757
petal_width       0.817954    -0.356544      0.962757     1.000000

In [6]:
x=data.drop('species',axis=1).values
y=data['species'].values

In [7]:
x.shape,y.shape

((150, 4), (150,))

In [8]:
y=y.reshape(-1,1)

In [9]:
y.shape

(150, 1)

In [11]:
missing_values=data.isnull().sum()
missing_values[0:20]

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [15]:
iris=load_iris()

In [16]:
iris.data[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [18]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [20]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [21]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [22]:
iris.data.shape

(150, 4)

In [25]:
x_train,x_test,y_train,y_test=train_test_split(iris.data,iris.target,test_size=0.30)

In [26]:
x_train,x_test

(array([[5.5, 4.2, 1.4, 0.2],
        [6.1, 2.9, 4.7, 1.4],
        [4.9, 3. , 1.4, 0.2],
        [5.8, 2.7, 5.1, 1.9],
        [5.1, 3.8, 1.6, 0.2],
        [4.9, 3.6, 1.4, 0.1],
        [5. , 3.4, 1.5, 0.2],
        [6.7, 3. , 5. , 1.7],
        [5. , 3.5, 1.3, 0.3],
        [5.4, 3.9, 1.3, 0.4],
        [4.8, 3.4, 1.6, 0.2],
        [6.2, 2.9, 4.3, 1.3],
        [4.9, 3.1, 1.5, 0.2],
        [5.7, 2.5, 5. , 2. ],
        [5.7, 3.8, 1.7, 0.3],
        [4.4, 2.9, 1.4, 0.2],
        [7.3, 2.9, 6.3, 1.8],
        [5. , 3. , 1.6, 0.2],
        [5.9, 3. , 5.1, 1.8],
        [5.1, 3.5, 1.4, 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [5.6, 2.8, 4.9, 2. ],
        [5. , 3.6, 1.4, 0.2],
        [6.5, 3.2, 5.1, 2. ],
        [5.4, 3.9, 1.7, 0.4],
        [6.1, 3. , 4.6, 1.4],
        [6.7, 3. , 5.2, 2.3],
        [5. , 3.2, 1.2, 0.2],
        [6. , 2.2, 4. , 1. ],
        [5.2, 2.7, 3.9, 1.4],
        [7.1, 3. , 5.9, 2.1],
        [5.5, 2.3, 4. , 1.3],
        [6.7, 3.3, 5.7, 2.5],
        [5

In [27]:
x_train.shape,x_test.shape

((105, 4), (45, 4))

In [28]:
y_train.shape,y_test.shape

((105,), (45,))

In [29]:
y_train=y_train.reshape(-1,1)
y_test=y_test.reshape(-1,1)

In [30]:
knn=KNeighborsClassifier(n_neighbors=1)
knn.fit(x_train,y_train)

/usr/local/lib/python3.9/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=1)

In [31]:
y_pred=knn.predict(x_test)

In [33]:
knn.score(x_train, y_train), knn.score(x_test, y_test)

(1.0, 0.9555555555555556)

In [34]:
confusion_matrix(y_test,y_pred)

array([[15,  0,  0],
       [ 0, 15,  1],
       [ 0,  1, 13]])

In [36]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       0.94      0.94      0.94        16
           2       0.93      0.93      0.93        14

    accuracy                           0.96        45
   macro avg       0.96      0.96      0.96        45
weighted avg       0.96      0.96      0.96        45

